global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'fastapi_app'
    static_configs:
      - targets: ['app:8000']

  # Добавьте сюда конфигурацию для сбора метрик вашего FastAPI приложения,
  # когда вы интегрируете экспортер метрик в него.
  # Например:
  # - job_name: 'fastapi_app'
  #   static_configs:
  #     - targets: ['host.docker.internal:8000'] # или ваш реальный хост и порт приложения 