"""add_role_to_users_and_user_id_to_artists

Revision ID: 0663bc15b5fd
Revises: aedb1e65e7f9
Create Date: 2025-06-02 01:08:31.009559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0663bc15b5fd'
down_revision: Union[str, None] = 'aedb1e65e7f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_artists_user_id'), 'artists', ['user_id'], unique=True)
    op.create_foreign_key(None, 'artists', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=False, server_default='listener'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_constraint(None, 'artists', type_='foreignkey')
    op.drop_index(op.f('ix_artists_user_id'), table_name='artists')
    op.drop_column('artists', 'user_id')
    # ### end Alembic commands ###
